spring:
  application:
    name: core

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    open-in-view: false
  datasource:
    url: jdbc:mysql://localhost:3306/bank
    username: user
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver

springdoc:
  swagger-ui:
    enabled: true
    path: /swagger-ui.html